### ISSUE TITLE
Very outdated gcc in conda-forge causing CyLP not to build.

### ISSUE THREAD

**Issue by rcjackson** [coin-or/CyLP#65]
When I try and build @jjhelmus's branch I get the following error:

gcc -pthread -B /home/rjackson/anaconda3/envs/adi_env3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./cylp/cpp -I./cylp/cy -I/home/rjackson/anaconda3/envs/adi_env3/include/coin -I/home/rjackson/anaconda3/envs/adi_env3/lib/python3.6/site-packages/numpy/core/include -I. -I/home/rjackson/anaconda3/envs/adi_env3/include/python3.6m -c cylp/cpp/IClpPrimalColumnPivotBase.cpp -o build/temp.linux-x86_64-3.6/cylp/cpp/IClpPrimalColumnPivotBase.o -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /home/rjackson/anaconda3/envs/adi_env3/gcc/include/c++/cstdint:35:0,
from /home/rjackson/anaconda3/envs/adi_env3/include/coin/CoinTypes.hpp:15,
from /home/rjackson/anaconda3/envs/adi_env3/include/coin/CoinHelperFunctions.hpp:24,
from /home/rjackson/anaconda3/envs/adi_env3/include/coin/CoinIndexedVector.hpp:20,
from cylp/cpp/IClpPrimalColumnPivotBase.h:6,
from cylp/cpp/IClpPrimalColumnPivotBase.cpp:1:
/home/rjackson/anaconda3/envs/adi_env3/gcc/include/c++/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support for the \

I tracked this down to the very, very old version of gcc that is in conda-forge (4.8.5). I got it to build with gcc 6.3.0, so I would _not_ use the conda-forge gcc to try and build CyLP. I wonder if there is a way to get gcc 6.3.0 as a conda package?

**Comment by tkralphs** [comment]
Cbc is building fine on conda-forge under Linux and OS X. `cylp` can easily be pip installed once Cbc has been conda installed. So this does not seem to be an issue anymore. If so, feel free to re-open.
