### ISSUE TITLE
Compilation problems with python 3.4

### ISSUE THREAD

**Issue by lsorber** [coin-or/CyLP#15]
CyLP seems to be exactly what I'm looking for, but unfortunately I can't get it to compile with python 3.4 (using Anaconda 2.0.1).

**First problem** ("fixed" by deleting the contents of README.rst):

```
File "//anaconda/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 343: ordinal not in range(128)
```

**Second problem**: print statements in fixBinaries.py without parentheses. Just added some parentheses and this went away.

**Third problem** I don't know what to do with:

```
cylp/cy/CyClpDualRowPivotBase.cpp:5180:19: error: no member named 'f_tstate' in '_frame'
        (*frame)->f_tstate = tstate;
```
