### ISSUE TITLE
Issues installing under sierra 

### ISSUE THREAD

**Issue by scollis** [coin-or/CyLP#44]
This is mainly an informative issue.. I have fixed this for my own use and the issue seems to be in the Cbc install itself. 

Platform: MacOS Sierra 

Following instructions I get:
```
In file included from /Users/scollis/coin/include/coin/CoinHelperFunctions.hpp:24:
/Users/scollis/coin/include/coin/CoinTypes.hpp:15:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
```
Googling and clicking Stackoverflow yields:
http://stackoverflow.com/questions/32552249/opencv-cstdint-file-not-found

So I replaced:
#include <cstdint>
with
#include <tr1/cstdint>
in /Users/scollis/coin/include/coin/CoinHelperFunctions.hpp

The issue seems to come from the line above:
#ifdef COINUTILS_HAS_CSTDINT

Seems something is not being set right on ./configure 

Cbc version 2.9.8

NOTE: Same Cbc version works 100% on linux.. and from other reports on earlier OSX 

Again, likely not a thing for the devs on this package but an alert for those who may be stuck

**Comment by scollis** [comment]
Edited above.. Meant 2.9.8

**Comment by scollis** [comment]
Note: works with 2.8.9

**Comment by scollis** [comment]
We REALLY should encourage users compiling on OSX to use 2.8.9! I can not get it to work with 2.8.5 but 2.8.9 works..

**Comment by tkralphs** [comment]
If you can report this over in the Cbc project, that would be helpful. Cbc is built and tested on Sierra with `clang` on Travis and seems to be working fine: https://travis-ci.org/coin-or/Cbc/jobs/194267846. It looks like you're using `gcc`, though. Anyway, we can get this patched up if you can nail down what the problem is.

**Comment by tkralphs** [comment]
Closing this, as it is a problem with Cbc and likely fixed by now.
