### PR TITLE
Python 3 support for CyLP

### LINKED ISSUE #15: Compilation problems with python 3.4
CyLP seems to be exactly what I'm looking for, but unfortunately I can't get it to compile with python 3.4 (using Anaconda 2.0.1).

**First problem** ("fixed" by deleting the contents of README.rst):

```
File "//anaconda/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 343: ordinal not in range(128)
```

**Second problem**: print statements in fixBinaries.py without parentheses. Just added some parentheses and this went away.

**Third problem** I don't know what to do with:

```
cylp/cy/CyClpDualRowPivotBase.cpp:5180:19: error: no member named 'f_tstate' in '_frame'
        (*frame)->f_tstate = tstate;
```

### PR DESCRIPTION
**Pull request by jjhelmus**
- Changes needed for CyLP to work in Python 3.4.  
- A single code base is used which supports Python 2.7, 3.3, and 3.4.  
- Unit test pass in all of the above Python version.

closes #15

### CODE REVIEW

**Comment by sebastroy** [comment]
1b798eb has a mistake: it's missing a parenthesis at the end of the line:
print(0.5 * x * (x * G).T + np.dot(c, x) - self.objectiveOffset
in file QP.py

in the same commit in QPGen.py on the very first line it's missing a "t" to import:
from __future__ impor print_function

I also get an error when executing "python setup.py install" (but I have it with pip install too...):
 writing cylp.egg-info/PKG-INFO
Traceback (most recent call last):
  File "setup.py", line 418, in <module>
    package_data={"cylp": ['cpp/*.cpp', 'cpp/*.hpp', 'cpp/*.h', 'VERSION']},)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 392, in run
    install.run(self)
  File "/usr/lib/python3.5/site-packages/setuptools/command/install.py", line 65, in run
    orig.install.run(self)
  File "/usr/lib/python3.5/distutils/command/install.py", line 551, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/install_egg_info.py", line 33, in run
    self.run_command('egg_info')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 173, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 388, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.5/distutils/dist.py", line 1107, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.5/distutils/dist.py", line 1128, in write_pkg_file
    long_desc = rfc822_escape(self.get_long_description())
  File "/usr/lib/python3.5/distutils/util.py", line 471, in rfc822_escape
    lines = header.split('\n')
TypeError: a bytes-like object is required, not 'str'

I use python 3.5

**Comment by jjhelmus** [comment]
Good catch on those mistakes @sebastroy, I added a commit to fix these.  Investigating the install issue.

**Comment by sebastroy** [comment]
Great thanks!

**Comment by jjhelmus** [comment]
Commit 13d5619 seem to fix the install issue although it might have broken the bdist_mpkg and bdist_wininst commands in setup.py.  With commit 89ce697 and 7fd344c I am able to run `python setup.py bdist_mpkg` on my machine in Python 2.7 and Python 3.5 but it fails with lines concerning pax failing:

```
pax: Cpio header field is too small to store file ./cylp/VERSION
pax: Cpio header field is too small to store file ./cylp-0.7.4-py2.7.egg-info
pax: Cpio header field is too small to store file ./cylp-0.7.4-py2.7.egg-info/dependency_links.txt
pax: Cpio header field is too small to store file ./cylp-0.7.4-py2.7.egg-info/not-zip-safe
pax: Cpio header field is too small to store file ./cylp-0.7.4-py2.7.egg-info/PKG-INFO
pax: Cpio header field is too small to store file ./cylp-0.7.4-py2.7.egg-info/requires.txt
pax: Cpio header field is too small to store file ./cylp-0.7.4-py2.7.egg-info/SOURCES.txt
pax: Cpio header field is too small to store file ./cylp-0.7.4-py2.7.egg-info/top_level.txt
error: command '/bin/pax' failed with exit status 1
```
Unfortunately my knowledge of bdist_mpkg is limited and I have no idea where to begin to debug this.  I get the same error messages on the current master so this may be limited to my machine.

I have no way of easily testing the bdist_wininst command.

**Comment by sebastroy** [comment]
I'm on linux myself... If I replace the call to getBdistFriendlyString and use plain "u" like the other two lines, install works but it possibly breaks the 2.7 version... In a nutshell, the issue is under python 2, str = bytes and under 3, bytes = bytes.

**Comment by jjhelmus** [comment]
Wanted to bump this PR and see if there was anything blocking this from being merged.  I am very interested in having a Python 3 version of CyLP and am willing to fix up any outstanding issues.

**Comment by sebastroy** [comment]
Fine by me

**Comment by tkralphs** [comment]
I've helped out a little with the maintenance of CyLP in the past and when I find some time, I'll try to attend to some of the pull requests piling up here, including this one. I'm still stuck in Python 2 myself :).

**Comment by jjhelmus** [comment]
Just wanted to bump this thread again.  Is there anything that I can do to get this include in CyLP?  I have a number of users who are interested in moving to Python 3 and this package is holding them back.

**Comment by tkralphs** [comment]
Thanks for the bump and the patience. Now that the semester is over, I'll start working through my (long) list of software maintenance tasks. Hopefully, we can get this integrated soon.

**Comment by jjhelmus** [comment]
Any chance this can be reviewed or merged?  I have users asking for the version of CyLP which supports Python 3.  I'm happy to rebase if it helps.

**Comment by sebastroy** [comment]
I've moved on to another library since then but I might give it a shot if it gets the python 3 upgrade...

**Comment by tkralphs** [comment]
Sorry, this still hasn't percolated to the top of the pile, but still on my TODO list.

**Comment by scollis** [comment]
Ping.. I am almost entirely 3 now.. Would be great to see this in the master branch

**Comment by RhysU** [comment]
Ditto on a desire to see this in master.

**Comment by Guzzii** [comment]
It would be really great to see python3 support from CyLP

**Comment by scollis** [comment]
Are we going to see action on this?

**Comment by SRserves85** [comment]
Bump, Is this ever happening?

**Comment by tkralphs** [comment]
I would still like to get back to CyLP and spend some time addressing the backlog of PRs, but I have obviously lost credibility in claiming this will happen. I will try to find a weekend soon when I can play with it. Obviously, it is not difficult to merge the PR. The time consuming part is testing. If those who have been using CyLP with Python 3 can post and say what their experience has been, it would be helpful in getting a level of comfort.

**Comment by sschnug** [comment]
I did not use this pull-request extensively, but i never approached problems!

While documentation and (mostly) missing development is depressing, it's still a very interesting project and official python3 support would be great!

(Two examples: [footrule-ranking (Clp)](https://github.com/sschnug/footrule_ranking), [kemeny-ranking (Cbc)](https://github.com/sschnug/kemeny_ranking))

**Comment by scollis** [comment]
We are now just redirecting folks for Py-ART to use the @jjhelmus branch. Having master fork updated with jjhelmus/py3 would be great

**Comment by scollis** [comment]
All, and specifically @tkralphs , We are at the point now that I am considering creating a fork with @jjhelmus 's work, making his py3 branch master and using that for Py-ART. This is a great project by we need a Py3 compatible master branch

**Comment by tkralphs** [comment]
I don't think a fork would be in anyone's best interest. Although this is not exactly my project, I do have the ability to add collaborators and I think I said at some point that I would be happy to hear from anyone who is willing to help, though maybe that got lost in the fray. The implication of the above comment is that there are people who would be happy to help. I would want to have some discussions with those people to make sure we're on the same page, but this seems to be the way forward.

**Comment by scollis** [comment]
Ok! I can help.. It looks like we have some conflicts.

**Comment by scollis** [comment]
@jjhelmus was it just Py3 compatibility issues or did you refactor? I am wondering if I should start with the current master and work from that or try to resolve the conflicts.

**Comment by scollis** [comment]
Actually now I look at the commits it looks quite involved.

**Comment by jjhelmus** [comment]
I created this patch over two years, I do not recall what all was done.  

Unfortunately, I do not have the time to re-work the patches or otherwise move this forward.  I'd be happy for someone else to pick up this work but I cannot offer any help myself.

**Comment by scollis** [comment]
No worries and understand @jjhelmus

**Comment by tkralphs** [comment]
As there haven't been very many commits since this PR was created and such commits were not very involved, I hope that resolving the conflicts would be not be too difficult. @scollis, perhaps we can schedule a face-to-face meeting and discuss a strategy? It would certainly be helpful to have someone who's using CyLP regularly and has a little bandwidth to push this forward. I'll actually be using CyLP with students in the next month or two and I'm sure they will be wanting to use Python 3, so between the two of us, we should be able to get this going.

**Comment by sebastroy** [comment]
My rule of thumb for "dead" projects is last commit more than 4-6mo ago. 

For what it's worth, we are using ortools now. It was a bit clunky a few years ago but it came a long way since then and is very stable. It does not have 100% all the cbc features (neither does CyLP for that matter) but it had enough for us. Unlike pulp, it does interface with the coin-or library rather than launch cbc in a shell wrapped in python code.

**Comment by scollis** [comment]
Hey @SteveDiamond We still use it.. I have been very slack in taking @tkralphs on his offer.. Having enough trouble with Py-ART which uses CyLP.

**Comment by scollis** [comment]
What would be amazing is a LP code in Scipy.optimize or suchlike

**Comment by tkralphs** [comment]
I'm still here and still hoping for a co-maintainer :). Although I have zero credibility left in terms of promises, I am going to be using CyLP myself in one of my classes this semester and will be trying to do some maintenance work over the next couple of weeks.

**Comment by tkralphs** [comment]
I just re-generated the Cython files and updated this PR in #67.

**Comment by tkralphs** [comment]
I posted a beta version with Python 3 support to Pypi: 
```
pip install --pre cylp
```
There is a binary wheel for Windows, but you still need to build Cbc before installing on Linux and OS X.

**Comment by tkralphs** [comment]
I seem to have figured out bug that prevented Cython 0.29 from properly re-generating the files. I re-generated the files once again with Cython 0.29 and just pushed a binary wheel up for Python 3.7 on Windows. With a little more testing, I'll be ready to merge and release an official Python 3 version.
